[package]
name = "humble_trader"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
reqwest = {version = "0.12.4", features = ["json"]}
websocket = "0.27.1"
derive_more = "^0.99"
tokio = {version = "1.37.0", features = ["full"]}



